define([], function () {
    return {
        VEHICLE_LIST_REQUEST: "VehicleListRequest",
        VEHICLE_LIST_RESPONSE: "VehicleListResponse",
        VEHICLE_SCENARIO_LIST_REQUEST: "VehicleScenarioListRequest",
        VEHICLE_SCENARIO_LIST_RESPONSE: "VehicleScenarioListResponse",
        VEHICLE_SCENARIO_ADD_REQUEST: "VehicleScenarioAddRequest",
        VEHICLE_SCENARIO_ADD_RESPONSE: "VehicleScenarioAddResponse",
        VEHICLE_SCENARIO_REMOVE_REQUEST: "VehicleScenarioRemoveRequest",
        VEHICLE_SCENARIO_REMOVE_RESPONSE: "VehicleScenarioRemoveResponse",
        VEHICLE_REQUEST: "VehicleRequest",
        VEHICLE_RESPONSE: "VehicleResponse",
        MAP_LIST_REQUEST: "MapListRequest",
        MAP_LIST_RESPONSE: "MapListResponse",
        LAYER_CONFIGURATION_LIST_REQUEST: "LayerConfigurationListRequest",
        LAYER_CONFIGURATION_LIST_RESPONSE: "LayerConfigurationListResponse",
        LAYER_CONFIGURATION_CREATE_REQUEST: "LayerConfigurationCreateRequest",
        LAYER_CONFIGURATION_CREATE_RESPONSE: "LayerConfigurationCreateResponse",
        LAYER_CONFIGURATION_REMOVE_REQUEST: "LayerConfigurationRemoveRequest",
        LAYER_CONFIGURATION_REMOVE_RESPONSE: "LayerConfigurationRemoveResponse",
        LAYER_CONFIGURATION_UPDATE_REQUEST: "LayerConfigurationUpdateRequest",
        LAYER_CONFIGURATION_UPDATE_RESPONSE: "LayerConfigurationUpdateResponse",
        TERRAIN_STATE_REQUEST: "TerrainStateRequest",
        TERRAIN_STATE_RESPONSE: "TerrainStateResponse",
        TERRAIN_STATE_UPDATE_REQUEST: "TerrainStateUpdateRequest",
        BUILDING_STATE_REQUEST: "BuildingStateRequest",
        BUILDING_STATE_RESPONSE: "BuildingStateResponse",
        BUILDING_STATE_UPDATE_REQUEST: "BuildingStateUpdateRequest",
        INCIDENT_LIST_REQUEST: "IncidentListRequest",
        INCIDENT_LIST_RESPONSE: "IncidentListResponse",
        INCIDENT_CREATE_REQUEST: "IncidentCreateRequest",
        INCIDENT_CREATE_RESPONSE: "IncidentCreateResponse",
        INCIDENT_REMOVE_REQUEST: "IncidentRemoveRequest",
        INCIDENT_REMOVE_RESPONSE: "IncidentRemoveResponse"
    };
});